- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: sample ec2 key
      ec2_key:
        name: samantha
        region: us-east-1
      register: keyout
    - debug:
        var: keyout
    - name: store the login details
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./sample-key.pem
      when: keyout.changed
      
    